### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by lihaoyu1234** [Kushim-Jiang/Pinyin-Sans#1]
1. 建议把 Basic Latin 区块补全。
2. 能否把大写英文字母 I 及相关字符改成类似于衬线体的形式（即原字体中的 `0xA7AE` 样式的），以便和小写字母 l 区分开来？
3. 能否把不在 Unicode 里的字符在 PUA 中备份一下？

**Comment by Hulenkius** [comment]
1. 本项目的基础字体 "Basically A Sans Serif" 已经填满了基础拉丁字母区块，作为拼音字体不需要其他字符，请自行取用。
2. 大写 I 只可能以带调的形式出现在专名语素中，根本不可能和小写 l 混淆。而且字体中已经包含了“工”形的字母 I 字符作为异体选择。
3. 本项目已经用连字实现了所有非编码字形，不需要再使用自定义区块。

**Comment by Kushim-Jiang** [comment]
「不在 Unicode 里的字符」是臆想，「赋予 Private User Area 内的码位」是坏毛病。
